import type { Candle, Direction, IndicatorSignal } from "../types";

const clamp = (v: number, min = -100, max = 100) => Math.max(min, Math.min(max, v));
const mean = (v: number[]) => v.reduce((a, b) => a + b, 0) / v.length;
const std = (v: number[]) => { const m = mean(v); return Math.sqrt(mean(v.map(x => (x - m) ** 2))); };
const direction = (score: number): Direction => score > 70 ? "strong_up" : score > 15 ? "up" : score < -70 ? "strong_down" : score < -15 ? "down" : "neutral";
const strength = (score: number) => Math.abs(score) > 70 ? "very_strong" : Math.abs(score) > 38 ? "strong" : Math.abs(score) > 15 ? "moderate" : "weak" as const;
const ema = (values: number[], period: number) => { const k = 2 / (period + 1); return values.reduce<number[]>((out, x) => [...out, out.length ? x * k + out[out.length - 1] * (1 - k) : x], []); };
function regression(values: number[]) { const n = values.length; const xbar = (n - 1) / 2, ybar = mean(values); const den = values.reduce((a, _, i) => a + (i - xbar) ** 2, 0); const slope = values.reduce((a, y, i) => a + (i - xbar) * (y - ybar), 0) / den; const total = values.reduce((a, y) => a + (y - ybar) ** 2, 0); const residual = values.reduce((a, y, i) => a + (y - (ybar + slope * (i - xbar))) ** 2, 0); return { slope, r2: total ? 1 - residual / total : 0 }; }
function rsi(values: number[], period = 14) { const d = values.slice(-period - 1).slice(1).map((v, i) => v - values.slice(-period - 1)[i]); const gain = mean(d.map(x => Math.max(x, 0))); const loss = mean(d.map(x => Math.max(-x, 0))) || 0.0001; return 100 - 100 / (1 + gain / loss); }
function adxApprox(c: Candle[]) { const recent = c.slice(-15); const ranges = recent.map(x => x.high - x.low); const moves = recent.slice(1).map((x, i) => x.close - recent[i].close); const plus = mean(moves.map(x => Math.max(x, 0))), minus = mean(moves.map(x => Math.max(-x, 0))); const atr = mean(ranges) || .01; const pdi = 100 * plus / atr, mdi = 100 * minus / atr; return { adx: Math.min(65, 100 * Math.abs(pdi - mdi) / (pdi + mdi || 1)), pdi, mdi }; }
function signal(id: string, name: string, category: IndicatorSignal["category"], timeframe: IndicatorSignal["timeframe"], score: number, displayValue: string, description: string, confidence = 70, state?: string): IndicatorSignal { return { id, name, category, timeframe, score: Math.round(clamp(score)), direction: direction(score), strength: strength(score), displayValue, description, confidence, state }; }

export function calculateIndicators(candles: Candle[]) {
 const close = candles.map(c => c.close), current = close.at(-1)!, momentum = (hours: number) => (current / close.at(-hours - 1)! - 1) * 100;
 const m6 = momentum(6), m12 = momentum(12), m24 = momentum(24), m3d = momentum(Math.min(72, close.length - 1)); const broad = (m6 + m12 + m24 + m3d) / 4;
 const e8 = ema(close, 8).at(-1)!, e21series = ema(close, 21), e21 = e21series.at(-1)!, e50 = ema(close, 50).at(-1)!; const es = ((e8 > e21 ? 32 : -32) + (e21 > e50 ? 32 : -32) + (e21 - e21series.at(-5)!) / current * 1500);
 const reg = regression(close.slice(-48)); const regScore = clamp(reg.slope / current * 35000 * (0.3 + reg.r2)); const a = adxApprox(candles); const adxScore = clamp((a.pdi - a.mdi) * 2 + (a.adx - 20)); const rs = rsi(close); const zWindow = close.slice(-48), z = (current - mean(zWindow)) / (std(zWindow) || .01); const atr = mean(candles.slice(-14).map(c => c.high - c.low)); const atrBase = mean(candles.slice(-80).map(c => c.high - c.low)) || atr; const atrPct = Math.round(clamp(50 + (atr / atrBase - 1) * 80, 1, 99));
 const highs = candles.slice(-25, -1).map(c => c.high), lows = candles.slice(-25, -1).map(c => c.low); const breakoutScore = current > Math.max(...highs) ? 75 : current < Math.min(...lows) ? -75 : broad * 12;
 const structure = marketStructure(candles);
 return [
  signal("mom-6", "6H Momentum", "momentum", "1H", m6 * 70, `${m6 >= 0 ? "+" : ""}${m6.toFixed(2)}%`, "Short-term price change", 72), signal("mom-24", "24H Momentum", "momentum", "1H", m24 * 70, `${m24 >= 0 ? "+" : ""}${m24.toFixed(2)}%`, "One-day price change", 78), signal("mom-3d", "3D Momentum", "momentum", "4H", m3d * 55, `${m3d >= 0 ? "+" : ""}${m3d.toFixed(2)}%`, "Broad multi-session momentum", 81),
  signal("ema", "EMA Structure", "trend", "4H", es, e8 > e21 && e21 > e50 ? "8 > 21 > 50" : e8 < e21 && e21 < e50 ? "8 < 21 < 50" : "Mixed", "EMA alignment plus 21-period slope", 75), signal("regression", "Regression 48H", "trend", "4H", regScore, `R² ${reg.r2.toFixed(2)}`, `Slope ${(reg.slope >= 0 ? "+" : "") + reg.slope.toFixed(4)} JPY/hour`, Math.round(reg.r2 * 70 + 25)), signal("adx", "ADX / DI", "trend", "4H", adxScore, `ADX ${a.adx.toFixed(1)}`, `+DI ${a.pdi.toFixed(1)} · −DI ${a.mdi.toFixed(1)}`, Math.round(a.adx + 45)),
  signal("structure", "Market Structure", "structure", "4H", structure.score, structure.label, structure.description, structure.confidence), signal("msb", "MSB · Structure Break", "structure", "4H", structure.msbScore, structure.msbLabel, structure.msbDescription, structure.confidence), signal("order-block", "Order Block", "structure", "4H", structure.obScore, structure.obLabel, structure.obDescription, 62), signal("donchian", "Donchian 20", "structure", "1H", breakoutScore, breakoutScore > 50 ? "Upper Breakout" : breakoutScore < -50 ? "Lower Breakout" : "Inside Channel", "Current price against prior 24H range", 71),
  signal("rsi", "RSI 14", "overextension", "4H", (rs - 50) * 2, rs.toFixed(1), rs >= 70 ? "Bullish momentum is overextended" : rs <= 30 ? "Bearish momentum is overextended" : "Momentum balance", 70, rs >= 70 ? "overbought" : rs <= 30 ? "oversold" : undefined), signal("zscore", "Price Z-score", "overextension", "4H", z * 30, `${z >= 0 ? "+" : ""}${z.toFixed(2)}σ`, Math.abs(z) >= 2 ? "Statistically extended from 48H mean" : "Position relative to 48H mean", 68, z >= 2 ? "overbought" : z <= -2 ? "oversold" : undefined), signal("atr", "ATR 14", "volatility", "4H", broad * 10, `${atr.toFixed(3)} JPY`, `Volatility percentile ${atrPct}%`, atrPct, atrPct > 70 ? "volatility_expansion" : undefined)
 ];
}

function marketStructure(c: Candle[]) { const w = c.slice(-50); const pivots: { i: number; kind: "H" | "L"; price: number }[] = []; for (let i = 2; i < w.length - 2; i++) { if (w[i].high > w[i-1].high && w[i].high > w[i-2].high && w[i].high > w[i+1].high && w[i].high > w[i+2].high) pivots.push({ i, kind:"H", price:w[i].high }); if (w[i].low < w[i-1].low && w[i].low < w[i-2].low && w[i].low < w[i+1].low && w[i].low < w[i+2].low) pivots.push({ i, kind:"L", price:w[i].low }); } const hs = pivots.filter(p=>p.kind==="H").slice(-2), ls=pivots.filter(p=>p.kind==="L").slice(-2), price=w.at(-1)!.close; const up=hs.length===2&&ls.length===2&&hs[1].price>hs[0].price&&ls[1].price>ls[0].price, down=hs.length===2&&ls.length===2&&hs[1].price<hs[0].price&&ls[1].price<ls[0].price; const lastHigh=hs.at(-1)?.price, lastLow=ls.at(-1)?.price; const bullBreak=lastHigh && price>lastHigh, bearBreak=lastLow && price<lastLow; const lastImpulse = [...w].reverse().find(x => bullBreak ? x.close < x.open : bearBreak ? x.close > x.open : false); return { score: up?62:down?-62:0, label:up?"HH / HL":down?"LH / LL":"Developing", description:up?"Higher highs and higher lows":down?"Lower highs and lower lows":"No confirmed swing sequence", confidence: pivots.length>3?75:48, msbScore:bullBreak?82:bearBreak?-82:0, msbLabel:bullBreak?"Bullish MSB":bearBreak?"Bearish MSB":"No active MSB", msbDescription:bullBreak?"Price broke the latest confirmed swing high":bearBreak?"Price broke the latest confirmed swing low":"Waiting for a confirmed swing break", obScore:bullBreak?45:bearBreak?-45:0, obLabel:lastImpulse?`${bullBreak?"Bullish":"Bearish"} OB`:"No active zone", obDescription:lastImpulse?`Last opposing candle before impulse: ${lastImpulse.low.toFixed(3)}–${lastImpulse.high.toFixed(3)}`:"Order-block zone requires a confirmed MSB" }; }
